[workspace]
# Use `borsh` crate CHANGELOG as top-level one
changelog_update = false

[[package]]
name = "borsh"
changelog_update = true
changelog_path = "./CHANGELOG.md"

[[package]]
name = "borsh-fuzz"
publish = false

[[package]]
name = "benchmarks"
publish = false
